extensions:

receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
        endpoint: 0.0.0.0:5317
      http:
        include_metadata: true
        endpoint: 0.0.0.0:5318

processors:
exporters:
  debug:
    verbosity: detailed
  nop:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [debug]
  extensions: []